### PR TITLE
Use screen media for PDF, with margins

### PR DESCRIPTION
**Pull request by JohnVeness**
Fixes issue #17

### CODE REVIEW

**Comment by JohnVeness** [comment]
Is this what you mean? Sorry, I'm new to most of this!

**Comment by EugeneLoy** [comment]
Yes, looks good now. Merged.

**Comment by JohnVeness** [comment]
I just wondered whether choosing screen media and setting the margins to 14mm is misplaced in Core.ts, given that it was a fix specific to edX, and I believe your tool also works with Coursera (although I haven't tried it and don't know how to try it with Coursera!). Should the media type and margin size be set somewhere in EdxDownloader.ts and CourseraDownloader.ts and passed to Core.ts/savePage() as parameters or similar?

**Comment by EugeneLoy** [comment]
>  just wondered whether choosing screen media and setting the margins to 14mm is misplaced in Core.ts, given that it was a fix specific to edX, and I believe your tool also works with Coursera

> Should the media type and margin size be set somewhere in EdxDownloader.ts and CourseraDownloader.ts and passed to Core.ts/savePage() as parameters or similar?

Don't worry about Coursera support for now. It is in experimental mode at this stage and once it matures I'll probably change project name to something like `course-archive` or `mooc-archive` to indicate that it is relevant not only to edX. At that point I'll make sure everything works nice on all platforms.

> although I haven't tried it and don't know how to try it with Coursera!

If you want to check it out, the workflow is pretty similar - pass email/password/course url and stuff will be downloaded. The only difference is that you'll be asked for captcha in ui window. At the moment the tool is capable of downloading quizz\exam feedbacks.

**Pull request merged**
